## Winterbloom Sword
titleraw @a[hasitem={item=fec:winterbloom_sword,location=slot.weapon.mainhand},scores={winterbloom_sword_ultimate_charge=..0,winterbloom_sword=0}] actionbar {"rawtext":[{"text":"§r : §a§l"},{"score":{"name":"*","objective":"winterbloom_sword_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"winterbloom_sword_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"winterbloom_sword_c3"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:winterbloom_sword,location=slot.weapon.mainhand},scores={winterbloom_sword_ultimate_charge=..0,winterbloom_sword=1}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"winterbloom_sword_c1"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"winterbloom_sword_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"winterbloom_sword_c3"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:winterbloom_sword,location=slot.weapon.mainhand},scores={winterbloom_sword_ultimate_charge=..0,winterbloom_sword=2}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"winterbloom_sword_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"winterbloom_sword_c2"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"winterbloom_sword_c3"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:winterbloom_sword,location=slot.weapon.mainhand},scores={winterbloom_sword_ultimate_charge=1..}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"winterbloom_sword_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"winterbloom_sword_c2"}},{"text":"s, §r : §a"},{"score":{"name":"*","objective":"winterbloom_sword_ultimate_charge"}},{"text":"/20"}]}

## Rage of Sakura
titleraw @a[hasitem={item=fec:rage_of_sakura,location=slot.weapon.mainhand},scores={rage_of_sakura=0}] actionbar {"rawtext":[{"text":"§r : §a§l"},{"score":{"name":"*","objective":"rage_of_sakura_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"rage_of_sakura_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"rage_of_sakura_c3"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:rage_of_sakura,location=slot.weapon.mainhand},scores={rage_of_sakura=1}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"rage_of_sakura_c1"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"rage_of_sakura_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"rage_of_sakura_c3"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:rage_of_sakura,location=slot.weapon.mainhand},scores={rage_of_sakura=2}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"rage_of_sakura_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"rage_of_sakura_c2"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"rage_of_sakura_c3"}},{"text":"s"}]}

## Murasama Calamity (ULTIMATE NOT READY ? READY)
titleraw @a[hasitem={item=fec:murasama_calamity,location=slot.weapon.mainhand},scores={murasama_calamity_c4=0..1,murasama_calamity=0}] actionbar {"rawtext":[{"text":"§r : §a§l"},{"score":{"name":"*","objective":"murasama_calamity_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"murasama_calamity_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"murasama_calamity_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"murasama_calamity_c4"}},{"text":"/2 Charge §r : §f"},{"score":{"name":"*","objective":"voltra_charge"}},{"text":"/100"}]}
titleraw @a[hasitem={item=fec:murasama_calamity,location=slot.weapon.mainhand},scores={murasama_calamity_c4=0..1,murasama_calamity=1}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"murasama_calamity_c1"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"murasama_calamity_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"murasama_calamity_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"murasama_calamity_c4"}},{"text":"/2 Charge §r : §f"},{"score":{"name":"*","objective":"voltra_charge"}},{"text":"/100"}]}
titleraw @a[hasitem={item=fec:murasama_calamity,location=slot.weapon.mainhand},scores={murasama_calamity_c4=0..1,murasama_calamity=2}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"murasama_calamity_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"murasama_calamity_c2"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"murasama_calamity_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"murasama_calamity_c4"}},{"text":"/2 Charge §r : §f"},{"score":{"name":"*","objective":"voltra_charge"}},{"text":"/100"}]}
titleraw @a[hasitem={item=fec:murasama_calamity,location=slot.weapon.mainhand},scores={murasama_calamity_c4=0..1,murasama_calamity=3}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"murasama_calamity_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"murasama_calamity_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"murasama_calamity_c3"}},{"text":"s, §r : §c§l"},{"score":{"name":"*","objective":"murasama_calamity_c4"}},{"text":"/2 Charge §r : §f"},{"score":{"name":"*","objective":"voltra_charge"}},{"text":"/100"}]}
titleraw @a[hasitem={item=fec:murasama_calamity,location=slot.weapon.mainhand},scores={murasama_calamity_c4=2..,murasama_calamity=0}] actionbar {"rawtext":[{"text":"§b : §a§l"},{"score":{"name":"*","objective":"murasama_calamity_c1"}},{"text":"s, §b : §e"},{"score":{"name":"*","objective":"murasama_calamity_c2"}},{"text":"s, §b : §e"},{"score":{"name":"*","objective":"murasama_calamity_c3"}},{"text":"s, §b : §eREADY! §r : §f"},{"score":{"name":"*","objective":"voltra_charge"}},{"text":"/100"}]}
titleraw @a[hasitem={item=fec:murasama_calamity,location=slot.weapon.mainhand},scores={murasama_calamity_c4=2..,murasama_calamity=1}] actionbar {"rawtext":[{"text":"§b : §e"},{"score":{"name":"*","objective":"murasama_calamity_c1"}},{"text":"s, §b : §a§l"},{"score":{"name":"*","objective":"murasama_calamity_c2"}},{"text":"s, §b : §e"},{"score":{"name":"*","objective":"murasama_calamity_c3"}},{"text":"s, §b : §eREADY! §r : §f"},{"score":{"name":"*","objective":"voltra_charge"}},{"text":"/100"}]}
titleraw @a[hasitem={item=fec:murasama_calamity,location=slot.weapon.mainhand},scores={murasama_calamity_c4=2..,murasama_calamity=2}] actionbar {"rawtext":[{"text":"§b : §e"},{"score":{"name":"*","objective":"murasama_calamity_c1"}},{"text":"s, §b : §e"},{"score":{"name":"*","objective":"murasama_calamity_c2"}},{"text":"s, §b : §a§l"},{"score":{"name":"*","objective":"murasama_calamity_c3"}},{"text":"s, §b : §eREADY! §r : §f"},{"score":{"name":"*","objective":"voltra_charge"}},{"text":"/100"}]}
titleraw @a[hasitem={item=fec:murasama_calamity,location=slot.weapon.mainhand},scores={murasama_calamity_c4=2..,murasama_calamity=3}] actionbar {"rawtext":[{"text":"§b : §e"},{"score":{"name":"*","objective":"murasama_calamity_c1"}},{"text":"s, §b : §e"},{"score":{"name":"*","objective":"murasama_calamity_c2"}},{"text":"s, §b : §e"},{"score":{"name":"*","objective":"murasama_calamity_c3"}},{"text":"s, §b : §a§lREADY! §r : §f"},{"score":{"name":"*","objective":"voltra_charge"}},{"text":"/100"}]}

## Windblade Claymore
titleraw @a[hasitem={item=fec:windblade_claymore,location=slot.weapon.mainhand},scores={windblade_claymore=0}] actionbar {"rawtext":[{"text":"§r : §a§l"},{"score":{"name":"*","objective":"windblade_claymore_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"windblade_claymore_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"windblade_claymore_c3"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:windblade_claymore,location=slot.weapon.mainhand},scores={windblade_claymore=1}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"windblade_claymore_c1"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"windblade_claymore_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"windblade_claymore_c3"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:windblade_claymore,location=slot.weapon.mainhand},scores={windblade_claymore=2}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"windblade_claymore_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"windblade_claymore_c2"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"windblade_claymore_c3"}},{"text":"s"}]}

## Blade of The End
titleraw @a[hasitem={item=fec:blade_of_the_end,location=slot.weapon.mainhand},scores={blade_of_the_end=0}] actionbar {"rawtext":[{"text":"§r : §a§l"},{"score":{"name":"*","objective":"blade_of_the_end_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"blade_of_the_end_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"blade_of_the_end_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"blade_of_the_end_c4"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:blade_of_the_end,location=slot.weapon.mainhand},scores={blade_of_the_end=1}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"blade_of_the_end_c1"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"blade_of_the_end_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"blade_of_the_end_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"blade_of_the_end_c4"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:blade_of_the_end,location=slot.weapon.mainhand},scores={blade_of_the_end=2}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"blade_of_the_end_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"blade_of_the_end_c2"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"blade_of_the_end_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"blade_of_the_end_c4"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:blade_of_the_end,location=slot.weapon.mainhand},scores={blade_of_the_end=3}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"blade_of_the_end_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"blade_of_the_end_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"blade_of_the_end_c3"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"blade_of_the_end_c4"}},{"text":"s"}]}

## Spear of Heart
titleraw @a[hasitem={item=fec:spear_of_heart,location=slot.weapon.mainhand},scores={spear_of_heart=0}] actionbar {"rawtext":[{"text":"§r : §a§l"},{"score":{"name":"*","objective":"spear_of_heart_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"spear_of_heart_c2"}},{"text":"s, §r §e"},{"score":{"name":"*","objective":"spear_of_heart_c3"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:spear_of_heart,location=slot.weapon.mainhand},scores={spear_of_heart=1}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"spear_of_heart_c1"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"spear_of_heart_c2"}},{"text":"s, §r §e"},{"score":{"name":"*","objective":"spear_of_heart_c3"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:spear_of_heart,location=slot.weapon.mainhand},scores={spear_of_heart=2}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"spear_of_heart_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"spear_of_heart_c2"}},{"text":"s, §r §a§l"},{"score":{"name":"*","objective":"spear_of_heart_c3"}},{"text":"s"}]}

## ZENITH
titleraw @a[hasitem={item=fec:zenith,location=slot.weapon.mainhand},scores={zenith=0}] actionbar {"rawtext":[{"text":"§r : §a§l"},{"score":{"name":"*","objective":"zenith_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c4"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c5"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:zenith,location=slot.weapon.mainhand},scores={zenith=1}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"zenith_c1"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"zenith_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c4"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c5"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:zenith,location=slot.weapon.mainhand},scores={zenith=2}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"zenith_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c2"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"zenith_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c4"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c5"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:zenith,location=slot.weapon.mainhand},scores={zenith=3}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"zenith_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c3"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"zenith_c4"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c5"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:zenith,location=slot.weapon.mainhand},scores={zenith=4}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"zenith_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"zenith_c4"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"zenith_c5"}},{"text":"s"}]}

## Eidolon 4 Staff
titleraw @a[hasitem={item=fec:eidolon_4_staff,location=slot.weapon.mainhand},scores={eidolon_4_staff=0}] actionbar {"rawtext":[{"text":"§r : §a§l"},{"score":{"name":"*","objective":"eidolon_4_staff_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"eidolon_4_staff_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"eidolon_4_staff_c3"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:eidolon_4_staff,location=slot.weapon.mainhand},scores={eidolon_4_staff=1}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"eidolon_4_staff_c1"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"eidolon_4_staff_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"eidolon_4_staff_c3"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:eidolon_4_staff,location=slot.weapon.mainhand},scores={eidolon_4_staff=2}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"eidolon_4_staff_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"eidolon_4_staff_c2"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"eidolon_4_staff_c3"}},{"text":"s"}]}

## Stars and Crescent
titleraw @a[hasitem={item=fec:stars_and_crescent,location=slot.weapon.mainhand},scores={stars_and_crescent=0}] actionbar {"rawtext":[{"text":"§r : §a§l"},{"score":{"name":"*","objective":"stars_and_crescent_c1"}},{"text":" Ticks, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c4"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c5"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:stars_and_crescent,location=slot.weapon.mainhand},scores={stars_and_crescent=1}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c1"}},{"text":" Ticks, §r : §a§l"},{"score":{"name":"*","objective":"stars_and_crescent_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c4"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c5"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:stars_and_crescent,location=slot.weapon.mainhand},scores={stars_and_crescent=2}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c1"}},{"text":" Ticks, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c2"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"stars_and_crescent_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c4"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c5"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:stars_and_crescent,location=slot.weapon.mainhand},scores={stars_and_crescent=3}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c1"}},{"text":" Ticks, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c3"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"stars_and_crescent_c4"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c5"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:stars_and_crescent,location=slot.weapon.mainhand},scores={stars_and_crescent=4}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c1"}},{"text":" Ticks, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"stars_and_crescent_c4"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"stars_and_crescent_c5"}},{"text":"s"}]}

## Shadow Revolver
titleraw @a[hasitem={item=fec:shadow_revolver,location=slot.weapon.mainhand},scores={shadow_revolver=0}] actionbar {"rawtext":[{"text":"§r : §a§l"},{"score":{"name":"*","objective":"shadow_revolver_rounds"}},{"text":"/8, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c4"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:shadow_revolver,location=slot.weapon.mainhand},scores={shadow_revolver=1}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"shadow_revolver_rounds"}},{"text":"/8, §r : §a§l"},{"score":{"name":"*","objective":"shadow_revolver_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c4"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:shadow_revolver,location=slot.weapon.mainhand},scores={shadow_revolver=2}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"shadow_revolver_rounds"}},{"text":"/8, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c1"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"shadow_revolver_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c4"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:shadow_revolver,location=slot.weapon.mainhand},scores={shadow_revolver=3}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"shadow_revolver_rounds"}},{"text":"/8, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c2"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"shadow_revolver_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c4"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:shadow_revolver,location=slot.weapon.mainhand},scores={shadow_revolver=4}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"shadow_revolver_rounds"}},{"text":"/8, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"shadow_revolver_c3"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"shadow_revolver_c4"}},{"text":"s"}]}

## Tenacity (Dual Mode)
titleraw @a[hasitem={item=fec:tenacity,location=slot.weapon.mainhand},scores={mythic_tenacity=0}] actionbar {"rawtext":[{"text":"§r : §a§l"},{"score":{"name":"*","objective":"tenacity_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c4"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:tenacity,location=slot.weapon.mainhand},scores={mythic_tenacity=1}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"tenacity_c1"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"tenacity_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c4"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:tenacity,location=slot.weapon.mainhand},scores={mythic_tenacity=2}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"tenacity_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c2"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"tenacity_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c4"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:tenacity,location=slot.weapon.mainhand},scores={mythic_tenacity=3}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"tenacity_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c3"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"tenacity_c4"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:tenacity_axe,location=slot.weapon.mainhand},scores={mythic_tenacity=0}] actionbar {"rawtext":[{"text":"§r : §a§l"},{"score":{"name":"*","objective":"tenacity_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c2_axe"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c3_axe"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c4_axe"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:tenacity_axe,location=slot.weapon.mainhand},scores={mythic_tenacity=1}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"tenacity_c1"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"tenacity_c2_axe"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c3_axe"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c4_axe"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:tenacity_axe,location=slot.weapon.mainhand},scores={mythic_tenacity=2}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"tenacity_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c2_axe"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"tenacity_c3_axe"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c4_axe"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:tenacity_axe,location=slot.weapon.mainhand},scores={mythic_tenacity=3}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"tenacity_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c2_axe"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"tenacity_c3_axe"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"tenacity_c4_axe"}},{"text":"s"}]}

## Reworked Tenacity
titleraw @a[hasitem={item=fec:reworked_tenacity,location=slot.weapon.mainhand},scores={reworked_tenacity=0}] actionbar {"rawtext":[{"text":"§r : §a§l"},{"score":{"name":"*","objective":"reworked_tenacity_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"reworked_tenacity_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"reworked_tenacity_c3"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:reworked_tenacity,location=slot.weapon.mainhand},scores={reworked_tenacity=1}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"reworked_tenacity_c1"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"reworked_tenacity_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"reworked_tenacity_c3"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:reworked_tenacity,location=slot.weapon.mainhand},scores={reworked_tenacity=2}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"reworked_tenacity_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"reworked_tenacity_c2"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"reworked_tenacity_c3"}},{"text":"s"}]}

## The Enigma
titleraw @a[hasitem={item=fec:the_enigma,location=slot.weapon.mainhand},scores={the_enigma=0}] actionbar {"rawtext":[{"text":"§r : §a§l"},{"score":{"name":"*","objective":"the_enigma_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"the_enigma_c2"}},{"text":"/40 Attacks, §r : §e"},{"score":{"name":"*","objective":"the_enigma_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"the_enigma_c4"}},{"text":"/3 Shot"}]}
titleraw @a[hasitem={item=fec:the_enigma,location=slot.weapon.mainhand},scores={the_enigma=1}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"the_enigma_c1"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"the_enigma_c2"}},{"text":"/40 Attacks, §r : §e"},{"score":{"name":"*","objective":"the_enigma_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"the_enigma_c4"}},{"text":"/3 Shot"}]}
titleraw @a[hasitem={item=fec:the_enigma,location=slot.weapon.mainhand},scores={the_enigma=2}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"the_enigma_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"the_enigma_c2"}},{"text":"/40 Attacks, §r : §a§l"},{"score":{"name":"*","objective":"the_enigma_c3"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"the_enigma_c4"}},{"text":"/3 Shot"}]}
titleraw @a[hasitem={item=fec:the_enigma,location=slot.weapon.mainhand},scores={the_enigma=3}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"the_enigma_c1"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"the_enigma_c2"}},{"text":"/40 Attacks, §r : §e"},{"score":{"name":"*","objective":"the_enigma_c3"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"the_enigma_c4"}},{"text":"/3 Shot"}]}

## Yamato
titleraw @a[hasitem={item=fec:yamato,location=slot.weapon.mainhand},scores={yamato=0}] actionbar {"rawtext":[{"text":"§r : §a§l"},{"score":{"name":"*","objective":"yamato_c1"}},{"text":"/5, §r : §e"},{"score":{"name":"*","objective":"yamato_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"yamato_c3"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:yamato,location=slot.weapon.mainhand},scores={yamato=1}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"yamato_c1"}},{"text":"/5, §r : §a§l"},{"score":{"name":"*","objective":"yamato_c2"}},{"text":"s, §r : §e"},{"score":{"name":"*","objective":"yamato_c3"}},{"text":"s"}]}
titleraw @a[hasitem={item=fec:yamato,location=slot.weapon.mainhand},scores={yamato=2}] actionbar {"rawtext":[{"text":"§r : §e"},{"score":{"name":"*","objective":"yamato_c1"}},{"text":"/5, §r : §e"},{"score":{"name":"*","objective":"yamato_c2"}},{"text":"s, §r : §a§l"},{"score":{"name":"*","objective":"yamato_c3"}},{"text":"s"}]}