scoreboard objectives remove moveCounter
scoreboard objectives remove jumpCounter
scoreboard objectives remove deathCounter
scoreboard objectives remove legendCounter
scoreboard objectives remove atkCounter
scoreboard objectives remove breakBlockCounter
scoreboard objectives remove placeBlockCounter
scoreboard objectives remove killCounter