scoreboard players reset @a atkp_delay
scoreboard players reset @a murasama_expansion
scoreboard players reset @a cosmic_tag
scoreboard players reset @a winterbloom_sword
scoreboard players reset @a rage_of_sakura
scoreboard players reset @a murasama_calamity
scoreboard players reset @a spear_of_heart
scoreboard players reset @a blade_of_the_end
scoreboard players reset @a windblade_claymore
scoreboard players reset @a eidolon_4_staff
scoreboard players reset @a zenith
scoreboard players reset @a stars_and_crescent
scoreboard players reset @a reworked_tenacity
scoreboard players reset @a shadow_revolver
scoreboard players reset @a mythic_tenacity
scoreboard players reset @a mythic_tenacity_shield
inputpermission set @a movement enabled
inputpermission set @a camera enabled
inputpermission set @a dismount enabled
inputpermission set @a lateral_movement enabled
inputpermission set @a jump enabled
inputpermission set @a sneak enabled
inputpermission set @a mount enabled
inputpermission set @a move_backward enabled
inputpermission set @a move_forward enabled
inputpermission set @a move_left enabled
inputpermission set @a move_right enabled